### PR TITLE
Peers Limiting and Balancing

### PR DESCRIPTION
**Pull request by amir-blox**

### CODE REVIEW

**Comment by lior-blox** [comment]
> @amir-blox should we start reviewing or it's not final yet?

@alonmuroch it's not final.
maybe we should have a template for how SIP should look like.

**Comment by alonmuroch** [comment]
@amir-blox should we start reviewing ?

**Comment by amir-blox** [comment]
> @amir-blox should we start reviewing ?

@lior-blox @alonmurochwe let's start IMO, we can change/add template afterwards if needed

**Comment by alonmuroch** [comment]
@amir-blox looks good to me, can you:
- make sure we can merge it without conflicts? 
- give it SIP # 3and add it to the all page and core page?
then I'll merge

**Comment by amir-blox** [comment]
Closing this SIP, and adding its content to network spec as it was already implemented.

https://github.com/bloxapp/ssv-spec/blob/network-docs/p2p/SPEC.md#peers-balancing

**Pull request closed without merging**
